### PR TITLE
Fix bugs in scala3 code #362 #360

### LINKED ISSUE #362: Using Scala 3 seriously breaks default value handing
Minimal example:

```scala
case class A(a: Int = 1)

import upickle.default._
implicit val rw: ReadWriter[A] = macroRW[A]

println(read[A]("{\"a\":2}"))
println(read[A]("{}"))
```

Expected (upickle 1.4.0, Scala 2.13.6):
```
A(2)
A(1)
```

Got (upickle 1.4.0, Scala 3.0.1):
```
A(2)
A(2)
```

God knows how many projects are silently corrupting their databases. Or leaking data from another user in their API calls. Since the parser is keeping and leaking state, everything is possible.

### PR DESCRIPTION
**Pull request by lihaoyi**
Fixes #362 #360

### CODE REVIEW

**Comment by lihaoyi** [comment]
@jodersky could I get a review

**Comment by lihaoyi** [comment]
Going to merge this; not sure what the binary compatibility complaint is, since this only touches scala 3 stuff

**Comment by lihaoyi** [comment]
Seems like the bincompat complaint is MIMA not liking the scala3 version bump. Just disabling MIMA for Scala3 for now

**Comment by lolgab** [comment]
Great @lihaoyi!
I'll check what's going on with MiMa when I have some time :)

**Comment by jodersky** [comment]
looks good, thanks for the fix!

**Pull request merged**
