### PR TITLE
Ensure that ujson.Value behaves properly as a direct target of reading/writing

### PR DESCRIPTION
**Pull request by lihaoyi**
The basic issue is that the `StringVisitor`/`StringReader` used for processing map keys when building JSON ASTs (https://github.com/com-lihaoyi/upickle/blob/d0b618e8b393089ca0e2bbea6648732a62227d9a/ujson/src/ujson/AstTransformer.scala#L30) was not sufficiently forgiving in accepting non-string types, which can be given to it when serializing a map with non-string keys.

This "loosening" of the input handling is in line with the general trend throughout uPickle, similar to how in 2.0.0 we allowed  https://github.com/com-lihaoyi/upickle/issues/385 we allowed numeric Scala types to accept JSON strings as input

This PR adds it to the test suite conversion matrix, so this code path is additionally exercised for every value in our test suite, and fixed another bug uncovered that crashed when directly writing `Infinity` and `-Infinity` to `ujson.Value`

Fixes https://github.com/com-lihaoyi/upickle/issues/433

### CODE REVIEW

**Review by lefou — COMMENTED** [review]
Looks reasonable to me. The binary breakage is ok here, but it's interesting, that it only breaks for Scala.js.

**Comment by lefou** [comment]
> Looks reasonable to me. The binary breakage is ok here, but it's interesting, that it only breaks for Scala.js.

Oh, it runs without `--keep-going`, so it probably also fails for all other platforms.

**Comment by lihaoyi** [comment]
We're going to release 3.0.0 next anyway right? which would mean binary compat breakage doesn't matter?

**Comment by lefou** [comment]
> We're going to release 3.0.0 next anyway right? which would mean binary compat breakage doesn't matter?

Exactly. The whole point about the `3.0.0-M1` pre-release was to get some binary breaking things in.

**Pull request merged**
