### PR TITLE
Support Scala Native - Scala 3

### PR DESCRIPTION
**Pull request by lolgab**
Bump Geny and Utest

### CODE REVIEW

**Comment by lolgab** [comment]
Since the libraries were updated to a binary incompatible version, I would bump the minor version. What do you think?

**Comment by jodersky** [comment]
Nice! I recently found out that Scala 3.1 has a new `-Yrelease` flag, which allows setting which minor version it will target. If it makes it easier, we could use Scala 3.1 (and newer versions in the future) everywhere in the build and set the flag to the lowest appropriate version.

**Comment by jodersky** [comment]
oh wait, that flag is only available from Scala 3.1.2-RC1 onwards

**Review by jodersky — APPROVED** [review]

**Comment by lolgab** [comment]
Yes, when `3.1.2` is out we can migrate the builds to do that :)

**Comment by lolgab** [comment]
@jodersky About the minor tagging. Does it sound like a good middle ground?

**Comment by jodersky** [comment]
I am fine with that

**Comment by jodersky** [comment]
actually wait one sec. What libraries were updated? Acyclic is only part of the tests, no?

**Comment by jodersky** [comment]
ah no, geny was updated too. Let's go for it then

**Pull request merged**
