### PR TITLE
Add Scala.js source map compiler flag

### LINKED ISSUE #431: Scala JS source maps, map to CI runner dir?
In my pet project, vite complains about source map errors. I believe one of the culprits to be upickle.

Here's a sample .js.map file.
```
{
"version": 3,
"file": "frontend.Page$$anon$1.js",
"mappings": "blah"
"sources": ["file:///C:/temp/ilsclaims/frontend/src/routes.scala", "file:///home/runner/work/upickle/upickle/implicits/src-3/upickle/implicits/CaseClassReader.scala", "https://raw.githubusercontent.com/scala/scala/v2.13.10/src/library/scala/collection/immutable/List.scala", "https://raw.githubusercontent.com/scala/scala/v2.13.10/src/library/scala/typeConstraints.scala", "https://raw.githubusercontent.com/scala/scala/v2.13.10/src/library/scala/Option.scala", "https://raw.githubusercontent.com/scala/scala/v2.13.10/src/library/scala/collection/mutable/ListBuffer.scala", "https://raw.githubusercontent.com/scala-js/scala-js/v1.12.0/library/src/main/scala/scala/scalajs/runtime/AnonFunctions.scala", "https://raw.githubusercontent.com/scala/scala/v2.13.10/src/library/scala/collection/Iterable.scala", "https://raw.githubusercontent.com/scala/scala/v2.13.10/src/library/scala/collection/IterableOnce.scala", "https://raw.githubusercontent.com/scala-js/scala-js/v1.12.0/scalalib/overrides-2.13/scala/reflect/Manifest.scala", "https://raw.githubusercontent.com/scala-js/scala-js/v1.12.0/scalalib/overrides-2.13/scala/collection/mutable/ArrayBuilder.scala"],
"names": ["CaseClassReaderPiece_this$2", "labels$2", "visitors$2", "defaultParams$2", "m$2", "internal-ceac6bf0dba5a7e47da1aeaaf3b9777a09e93427", "visitObject", "visitString", "visitorForKey", "this", "internal-b28b7af69320201d1cf206ebf28373980add1451", "internal-a08ca37f31725b66f4cce58b26ae7226a5925624", "make", "x$1", "arg1", "frontend.Page$ExposedEvent", "frontend.Page$$anon$2", "$outer"],
"lineCount": 142
}
```

I think the important part, is the second line of the "sources" property,  [home/runner/work/smithy4s/etc/etc](file:///home/runner/work/upickle/upickle/implicits/src-3/upickle/implicits/CaseClassReader.scala) line, which obviously doesn't exist in my local environment. Due to lurking discord, I believe the solution may look something like this;

https://discord.com/channels/632150470000902164/635668814956068864/1060561961810677760

https://github.com/typelevel/sbt-typelevel/blob/4da726ca021ea2c6459e8286d9ec49ab7c79a883/github/src/main/scala/org/typelevel/sbt/TypelevelScalaJSGitHubPlugin.scala#L35

I believe there to be a compiler flag, which could potentially point this back to this repository, for example.

### PR DESCRIPTION
**Pull request by Quafadas**
My attempt to fix #431 

I haven't been able to test this at all. I think the solution is "spiritually" correct, but getting upickle to build in my environment, is not a trivial undertaking. I'll try it on a home computer once I get the chance. I'm also not sure, if this should be a very different place in upickle or mill itself - making it a bit of a shot in the dark to debug through CI right now.

The idea is stolen from here; 
https://github.com/raquo/Laminar/blob/739cc0dbab319c685f28be30a1592b7d04347842/build.sbt#L78

### CODE REVIEW

**Comment by Quafadas** [comment]
This now compiles locally for me, so I guess it would have some chance of working. 

If it was possible to let it run through the CI, it may (?) to test, whether this change worked or not ...

**Comment by lolgab** [comment]
Hi @Quafadas and thank you for your contribution! Having proper sourceMap links is a great addition to the com-lihaoyi ecosystem.
There are some problems in the PR. `publishVersion` and `scalaVersion` are targets and you can't simply call toString on them, but you need to call apply, and be in another Task to do so.
I suggest you to call this command to check what is the result:
```
mill -w show upickle.js[2.13.10,1.10.1].scalacOptions 
```
Also checking [sbt-typelevel](https://github.com/typelevel/sbt-typelevel/blob/4da726ca021ea2c6459e8286d9ec49ab7c79a883/github/src/main/scala/org/typelevel/sbt/TypelevelScalaJSGitHubPlugin.scala#L35) they don't do anything specific for Scala 2.12 and 2.11 so you can just check if it's scala3 or not.
I checked cats-effect core scalacOptions and this is what it outputs:
```
-P:scalajs:mapSourceURI:file:/Users/lorenzo/scala/cats-effect/->https://raw.githubusercontent.com/typelevel/cats-effect/73d63c8f301df317efe39dcc7d12b79914aa9455/
```
So this lacks a trailing `/` after the path.
Also the path should be the base directory of the project (`T.workspace`), not the `millSourcePath`
It would look like something like this:
```scala
  private def sourceMapOption = T.task {
    val remoteSourcesPath = s"https://raw.githubusercontent.com/com-lihaoyi/upickle/${publishVersion()}/"
    val sourcesOptionName = if(isScala3(crossScalaVersion)) "-scalajs-mapSourceURI" else "-P:scalajs:mapSourceURI"
    s"$sourcesOptionName:${T.workspace}/->$remoteSourcesPath"
  }
  override def scalacOptions = super.scalacOptions() ++ Seq(sourceMapOption())
```

which outputs this:
```
"-P:scalajs:mapSourceURI:/Users/lorenzo/scala/upickle/->https://raw.githubusercontent.com/com-lihaoyi/upickle/3.0.0-M1-4-48f229-DIRTYa58c6001/"
```

Now, if you wanna be fancy and have some code that is portable to other repositories as well, you can derive the URL from `pomSettings()` (after fixing it, since it still points to the old URL (github.com/lihaoyi/upickle):

```scala
  private def sourceMapOption = T.task {
    val baseUrl = pomSettings().url.replace("github.com", "raw.githubusercontent.com")
    val sourcesOptionName = if(isScala3(crossScalaVersion)) "-scalajs-mapSourceURI" else "-P:scalajs:mapSourceURI"
    s"$sourcesOptionName:${T.workspace}/->$baseUrl/${publishVersion()}/"
  }
  override def scalacOptions = super.scalacOptions() ++ Seq(sourceMapOption())
```

This is the final draft.

**Comment by Quafadas** [comment]
@lolgab Oh wow - that is amazing feedback! Thankyou for taking the time - wonderfully educational too. 

As soon as I get a chance, I'll be taking another look...

**Comment by Quafadas** [comment]
@lefou @lolgab would it be possible to trigger CI again? It runs green on my fork now. 

One day I'll look at adding this to a mill plugin as practise for making a mill plugin, if it is not already done by then.  But it will not be soon, sadly :-( ... 

Thankyou again so much for your help.

**Comment by lefou** [comment]
@lolgab Is this good to merge?

**Comment by lolgab** [comment]
@lefou There were some problems that I fixed in the last commits. Let's wait for the CI and then I think we can merge.

**Comment by Quafadas** [comment]
@lolgab Thankyou so much again for your time.

**Comment by Quafadas** [comment]
I would be very happy to pick up the manual test once the release is out and will report back here.

**Comment by Quafadas** [comment]
@lefou @lolgab I think this can be left safely closed. I added upickle  3.0.0-M2 to a toy app and did two checks; 

1. In testvite.Main$.js.map which is a source map generated by site, I found links like this; 
"https://raw.githubusercontent.com/lihaoyi/upickle/3.0.0-M2/ujson/src/ujson/Readable.scala"
Which click through to the sources for upickle.

2. I generated an exception inside a upickle read block, which left a stack trace in the browser console, which looked like this; 
Screenshot 2023-02-06 at 21 15 37

That "Api.scala", is from upickle, and clicks right through to the sources on GitHub. 

So I conclude this works great - thank you both for you time!

**Comment by lefou** [comment]
@Quafadas Thank for reporting back!

**Pull request merged**
