### PR TITLE
Scala LTS 3.3.3

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by lihaoyi** [comment]
```scala
Error: [#0] [error] -- Error: /home/runner/work/upickle/upickle/upickle/test/src/upickle/ClassDefs.scala:209:34 
Error: [#0] [error] 209 |      implicit def rw: RW[ClsA] = default.macroRW
Error: [#0] [error]     |                                  ^^^^^^^^^^^^^^^
Error: [#0] [error]     |Exception occurred while executing macro expansion.
Error: [#0] [error]     |java.lang.ClassCastException: dotty.tools.dotc.ast.Trees$This cannot be cast to dotty.tools.dotc.ast.Trees$RefTree
Error: [#0] [error]     |	at scala.quoted.runtime.impl.QuotesImpl.scala$quoted$runtime$impl$QuotesImpl$reflect$Ref$$$_$apply$$anonfun$6(QuotesImpl.scala:446)
Error: [#0] [error]     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:3002)
Error: [#0] [error]     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$Ref$.apply(QuotesImpl.scala:446)
Error: [#0] [error]     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$Ref$.apply(QuotesImpl.scala:444)
Error: [#0] [error]     |	at upickle.implicits.macros.macros$package$.apply$1(macros.scala:260)
Error: [#0] [error]     |	at upickle.implicits.macros.macros$package$.applyConstructorImpl(macros.scala:268)
Error: [#0] [error]     |
Error: [#0] [error]     |---------------------------------------------------------------------------
Error: [#0] [error]     |Inline stack trace
Error: [#0] [error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error: [#0] [error]     |This location contains code that was inlined from macros.scala:224
Error: [#0] [error] 224 |inline def applyConstructor[T](params: Array[Any]): T = ${ applyConstructorImpl[T]('params) }
Error: [#0] [error]     |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: [#0] [error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error: [#0] [error]     |This location contains code that was inlined from macros.scala:224
Error: [#0] [error]  65 |        params => macros.applyConstructor[T](params)
Error: [#0] [error]     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: [#0] [error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error: [#0] [error]     |This location contains code that was inlined from macros.scala:224
Error: [#0] [error]  11 |    ReadWriter.join(macroR[T], macroW[T])
Error: [#0] [error]     |                    ^^^^^^^^^
Error: [#0] [error]      ---------------------------------------------------------------------------
[#2] [info] done compiling
```

**Comment by SethTisue** [comment]
maybe try it with 3.3.5-RC1-bin-20240712-4eb7668-NIGHTLY, as many 3.x PRs have now been backported to the 3.3 LTS series

**Comment by lihaoyi** [comment]
ohey, looks like it works.

Seems like we'll be able to bring back support for 3.x as long as 3.3.5 comes out some time in the near future

**Comment by sideeffffect** [comment]
I don't understand why it fails for Native :(

**Comment by sideeffffect** [comment]
@lihaoyi please run :pray:

**Comment by sideeffffect** [comment]
Done in
 * https://github.com/com-lihaoyi/upickle/pull/635

**Pull request closed without merging**
